# Generated by Django 4.0.6 on 2022-07-29 08:10

import Job.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0006_job_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='qualification',
            field=models.TextField(blank=True, default='', max_length=4000),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibility',
            field=models.TextField(blank=True, default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(upload_to=Job.models.image_upload),
        ),
    ]
