# Generated by Django 4.0.6 on 2022-07-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0007_job_qualification_job_responsibility_alter_job_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='qualification',
            field=models.TextField(default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='job',
            name='responsibility',
            field=models.TextField(default='', max_length=3000),
        ),
    ]
