# Generated by Django 4.0.6 on 2022-07-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0009_alter_job_qualification_alter_job_responsibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='qualification',
            field=models.TextField(default='', help_text='please put between lines  " , " ', max_length=4000),
        ),
        migrations.AlterField(
            model_name='job',
            name='responsibility',
            field=models.TextField(default='', help_text='please put between lines  " , " ', max_length=3000),
        ),
    ]
