# Generated by Django 4.0.6 on 2022-07-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0012_apply_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
